version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/packer/centos/scripts"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/golang"
    schedule:
      interval: "weekly"
