apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app.kubernetes.io/name: namespace-resource-quota
    app.kubernetes.io/instance: demo
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: quota
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/managed-by: manual
  name: namespace-resource-quota
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "2"
    requests.cpu: "1"
    requests.memory: 1Gi
    