apiVersion: v1
kind: LimitRange
metadata:
  labels:
    app.kubernetes.io/name: namespace-limits
    app.kubernetes.io/instance: demo
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: limit
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/managed-by: manual
  name: namespace-limits
spec:
  limits:
    - default:
        cpu: 500m
        memory: 200Mi
      defaultRequest:
        cpu: 200m
        memory: 100Mi
      max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 50m
        memory: 50Mi
      type: Container
