apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: namespace-limit-pod
    app.kubernetes.io/instance: namespace-limit-pod
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: pod
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/managed-by: manual
  name: namespace-limit-pod
spec:
  containers:
    - name: namespace-limit-pod
      image: nginx
      imagePullPolicy: Always
      resources:
        limits:
          memory: 200Mi
          cpu: 200m
        requests:
          memory: 100Mi
          cpu: 100m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CHOWN
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
          drop:
            - ALL
        readOnlyRootFilesystem: false
        runAsNonRoot: false
