apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: namespace-limit-deploy
    app.kubernetes.io/instance: namespace-limit-deploy
    app.kubernetes.io/version: v0.0.1
    app.kubernetes.io/component: deploy
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/managed-by: manual
  name: namespace-limit-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: namespace-limit
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: namespace-limit
        app.kubernetes.io/instance: namespace-limit
        app.kubernetes.io/version: v0.0.1
        app.kubernetes.io/component: deploy
        app.kubernetes.io/part-of: admin
        app.kubernetes.io/managed-by: manual
      name: namespace-limit
    spec:
      containers:
        - name: namespace-limit-pod
          image: nginx
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 100m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
                - NET_BIND_SERVICE
                - SETGID
                - SETUID
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: false
