---
- name: Install asdf
  ansible.builtin.command:
    chdir: /home/vagrant
    argv:
      - git
      - clone
      - https://github.com/asdf-vm/asdf.git
      - .asdf
      - --branch
      - v0.8.0
    creates: /home/vagrant/.asdf
