replicaCount: 1

image:
  repository: adgayle/book-library
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  hosts:
  - host: book-library.applications
    paths:
    - path: /
      pathType: ImplementationSpecific

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

application:
  port: 8080
  releaseMode: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
