# -*- mode: ruby -*-
# vi: set ft=ruby :
## vagrant file to create virtualbox workstation (vbw)
Vagrant.require_version ">= 2.2.0"

Vagrant.configure("2") do |config|
  # build the vm from centos 8
  config.vm.define "vbw", autostart: true do |vbw|
    vbw.vm.box              = "bento/centos-8"
    vbw.vm.box_check_update = true
    vbw.vm.hostname         = "vbw"

    # set the hostname and memory
    config.vm.provider :virtualbox do |vbw|
      vbw.customize ["modifyvm", :id, "--memory", 1024]
      vbw.customize ["modifyvm", :id, "--name", "vbw"]
    end
  end

  # configure the sync directory so I can copy files if needed
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775"]
end
