- package:
    state: absent
    name: "{{ old_docker_packages }}"

- yum_repository:
    name: docker-ce-stable
    file: docker-ce
    description: Docker Community Edition
    baseurl: "https://download.docker.com/linux/centos/{{ centos_version }}/{{ centos_arch }}/stable"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- package:
    state: latest
    name: "{{ docker_ce_packages }}"

- systemd:
    name: docker
    enabled: yes
    state: started

- user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
