# -*- mode: ruby -*-
# vi: set ft=ruby :
## vagrant file to create virtualbox workstation (developer)
Vagrant.require_version ">= 2.2.0"

Vagrant.configure("2") do |config|
  # build the vm from ubuntu 20.04
  config.vm.define "developer", autostart: true do |developer|
    developer.vm.box              = "bento/ubuntu-20.04"
    developer.vm.box_check_update = true
    developer.vm.hostname         = "developer"

    # set the hostname and memory
    config.vm.provider :virtualbox do |developer|
      developer.customize ["modifyvm", :id, "--memory", 2048]
      developer.customize ["modifyvm", :id, "--name", "developer"]
    end
  end

  # force port for vscode connection
  config.vm.network "forwarded_port", guest: 22, host: 2200, protocol: "tcp"

  # configure the sync directory so I can copy files if needed
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775"]

  # copy ansible provisioning to local machine
  config.vm.provision "file", source: "../../ansible", destination: "/home/vagrant/"

  # configure the developer with privileged ansible
  config.vm.provision :ansible_local do |privileged_ansible|
    privileged_ansible.install            = true
    privileged_ansible.become             = true
    privileged_ansible.install_mode       = "default"
    privileged_ansible.compatibility_mode = "2.0"
    privileged_ansible.playbook           = "/home/vagrant/ansible/developer-playbook.yml"
  end

  # install ansible.posix collection
  config.vm.provision :shell do |collection|
    collection.inline     = "ansible-galaxy collection install ansible.posix"
    collection.privileged = false
  end

  # configure the developer unprivileged with ansible
  config.vm.provision :ansible_local do |unprivileged_ansible|
    unprivileged_ansible.install            = true
    unprivileged_ansible.become             = false
    unprivileged_ansible.install_mode       = "default"
    unprivileged_ansible.compatibility_mode = "2.0"
    unprivileged_ansible.playbook           = "/home/vagrant/ansible/user-playbook.yml"
  end
end
