name: Push Book Library Image

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "golang/book-library"

env:
  REPOSITORY: book-library

jobs:
  push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.book-library
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:latest
