name: CI for Golang Book Library

on:
  push:
    paths:
      - "golang/book-library/*.go"
  pull_request:
    paths:
      - "golang/book-library/*.go"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: "1.19"

      - name: Install dependencies
        working-directory: "golang/book-library"
        run: |
          go mod download

      - name: Check for errors
        working-directory: "golang/book-library"
        run: |
          go vet .

      - name: Run tests
        working-directory: "golang/book-library"
        env:
          GIN_MODE: release
        run: |
          go test -v ./...
