name: Conditional Matrix

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - ".github/workflows/matrix-conditional.yaml"

jobs:
  evaluate:
    name: Evaluate conditional matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: [
          { name: "cluster-dev-usw2-b", region: "us-west-2" },
          { name: "cluster-dev-use1-b", region: "us-east-1" }, 
          { name: "cluster-dev-usw2-c", region: "us-west-2" },
          { name: "cluster-dev-use1-d", region: "us-east-1" }
        ]
    steps:
      - name: Print configuration
        run: |
          echo "cluster: ${{ matrix.cluster.name }}, region: ${{ matrix.cluster.region }}"
