name: Conditional Matrix

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - ".github/workflows/matrix-conditional.yaml"

jobs:
  evaluate:
    name: Evaluate conditional matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster: ["cluster-dev-usw2-b", "cluster-dev-use1-b", "cluster-dev-usw2-c", "cluster-dev-use1-d"]
    steps:
      - name: Get region us-west-2
        if: contains(${{ matrix.cluster }}, "usw2")
        run: |
          echo "CALC_AWS_REGION=us-west-2" >> $GITHUB_ENV

      - name: Get region us-east-1
        if: contains(${{ matrix.cluster }}, "use1")
        run: |
          echo "CALC_AWS_REGION=us-east-1" >> $GITHUB_ENV

      - name: Print region
        run: |
          echo "cluster: ${{ matrix.cluster }}, region: $CALC_AWS_REGION"
