# This workflow will validate the packer configuration files

name: packer validate

on:
  push:
    #branches: [ main ]
    paths:
    - 'packer/**/**.hcl'
    - 'packer/**/**.json'
  pull_request:
    #branches: [ main ]
    paths:
    - 'packer/**/**.hcl'
    - 'packer/**/**.hcl'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packer
      run: |
        wget -O /tmp/packer_${{ env.PACKER_VERSION }}_linux_amd64.zip https://releases.hashicorp.com/packer/1.6.6/packer_${{ env.PACKER_VERSION }}_linux_amd64.zip  
        unzip /tmp/packer_${{ env.PACKER_VERSION }}_linux_amd64.zip && sudo mv /usr/local/bin && sudo chmod a+x /usr/local/bin/packer
        rm /tmp/packer_${{ env.PACKER_VERSION }}_linux_amd64.zip
      env:
        PACKER_VERSION: 1.6.6
    - name: check packer hcl2 formatting
      working-directory: packer/centos/
      run:
        packer fmt -check
    - name: validate packer hcl2 syntax
      working-directory: packer/centos/
      run:
        packer validate
