# workflow will validate the packer configuration files

name: packer validate
on:
  push:
    paths:
    - '.github/workflows/packer.yml'
    - 'packer/centos/*.hcl'
    - 'packer/centos/*.json'
  pull_request:
    paths:
    - '.github/workflows/packer.yml'
    - 'packer/centos/*.hcl'
    - 'packer/centos/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup latest packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.6.6

    - name: Check packer hcl2 formatting
      working-directory: packer/centos/
      run:
        packer fmt -check .

    - name: Validate packer hcl2 syntax
      working-directory: packer/centos/
      run:
        packer validate -var "ssh_password=${{ secrets.PACKER_SSH_PASSWORD }}" .
